site_name: "Commit-0"

docs_dir: docs
nav:
  - Home: index.md
  - Commit0: setupdist.md
  - Agent: agent.md
  - API: api.md
  - Leaderboard: analysis.md
theme:
  name: material
  logo: "logo2.webp"

extra_css:
  - extra.css

markdown_extensions:
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.highlight
  - pymdownx.superfences
